{% set name = "redux" %}
{% set version = "4.2.0" %}
{% set sha256 = "83d2abfc5b18058291590009078964548220fbe44fa6ea606f8c14790495aef2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/reactjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g redux
  requires:
    - nodejs

about:
  home: https://github.com/reactjs/redux
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Predictable state container for JavaScript apps
  description: |
    Redux is a predictable state container for JavaScript apps.
  doc_url: http://redux.js.org/
  dev_url: https://github.com/reactjs/redux
