{% set name = "redux" %}
{% set version = "4.0.2" %}
{% set sha256 = "c66586a18d37784c64df286c4e7b6de54127bdf27ced742151a20d2417f176e9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/reactjs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g redux
  requires:
    - nodejs
   
about:
  home: https://github.com/reactjs/redux
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Predictable state container for JavaScript apps'
  description: |
    Redux is a predictable state container for JavaScript apps.
  doc_url: http://redux.js.org/
  dev_url: https://github.com/reactjs/redux
  
extra:
  recipe-maintainers:
    - cshaley
    - sannykr
