travis:
  secure:
    BINSTAR_TOKEN: NZJubiZ87WsAE2UOV5Bh6dbpm/6WCsM5i7UfOq3YsbQUdH88wGdror9jnORvQYDAa42GbZXlxnb4sUIAVFSusTPaFS64su/jV6Zp7nMbDrMiGHU6vRzG6fL14twXZs0qdvnkdQHbCdAU2yJ9B12uKe2dL9FhHYzsSaFyuFIVK55WE5fKRdjJ0guQxL6KeIqMKD9xd+FO93weLZzkkaAJ53qM9G74KKSIjdI0XUqacb3jdISlYXNO0NPpTRqoKKXE439rDZy97HbZ2C2FY9gt+x8COvACG3wtooipEX25HIWvWJXqE9GaekRiYQUDy5v/VKQ+/RhO1NFcoY7QWjR4/KrTY7k5eshfVsXhaMRjUyBhWIku8P2c2lT/NYr0FEWhCEanCFo2sItFETqgf8XVgji+/Qs63AIOrJan2bxtAca4vh4WMfGARbAkGjY8aUFz4l3USfwL7RRwWDDLJX2jvSCQJLNCVGZFoj2NvRg9oGZLcztts2mbNHai3qK/MG8dD3/riRKTwps6z4evGJ8q9q6WX5mbEWCj+W02iCR0x1lAI8ar/mM3sYdIZmKLWDqcOACdNLSu75vjBdk0dZL2rrBYtxn40aDPQk9wsEAKOHIvEHv0bBYmWGEAE3MCQ//dkhgxD7jBCfnbyj482kplyMVWuvjUouHwa/AinsCGmys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
