travis:
  secure:
    BINSTAR_TOKEN: DZrBTMHTfafpqUmJ0F7bpgTDzgUn95B0vpHB7P0/V8bFHZVTS8GYKz6cC8R9Eok1f6VWAlj9KfWWb9e3s/XYvCFAfjTUmVMsAMS5or2Af1kt6ppWeaX3A3dRGA1Z754E09rYpWmuiAlMqMRIpSXm1LRhYgVYshgBTyVwYBJy5dNbeta2EE2/0wsMEpl87PK943xp9RruwqTr6IklBllp/oVVCF2oIn69QlMn3T2F3hkbMaiBHvgH/VG2lamje/xd+tDa5x6Q/Or/Q6kERO8PHw0XiielXrlac/WTdYXUSCt90QxsTL7/CYb0/LwLVkj1sHQCjTisQbb9GtZ21ZfPRT0Yc9nYRPCr1BKPKO0HCD3IwG+3rYeXUWoekZnL2nhx11jbaL8n0OSLpH63eWyguvTKxGrDlBhN+VXPnMQF9L7n4X7YIe5iASP2bdV/RBfj3O0Cc/8Y7h+rb8aNzjlqFR1lkiZCgmdUr1JoTEKIjIjw60MCnR0iI2nc4MuVFbGN/Fki/7Q+vgH+34DI0+QmJUwo565TH4SDuV2oHuAgIoYNtegPdxGHkrPwqAD/sCKMmF9Wh+7iBD/5SssrdUJimj91jtCXKfrIEHDlMqZ0EIOlpEk7w8xUurG8SF2jAoAlJugFwZuQ8v+kuV0VNCSw1uDmXqqDFhzGqL+M2oqf9dc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
