travis:
  secure:
    BINSTAR_TOKEN: ss3ml9W6FyvO6sYHybjh9CqX3GhaOO0mj+dr+DQqJVyJ7uPkEkhyghjT+2/lIL+e9Zv6jdDu5aYhPE1YRYSssnZzCnu32x4BbFkR5AKSXw/v+CFASTSOPj2QBltVF0FMQOT6cJ+GksUgCIgblxPmQjVapcojwAcMJqgafFRcigF22C2jMJzCrJA6AqQe45bb7ceJ5JlnE/CRO1B/dVAXkAdYJOEZzLW1BEF3ZvbyU9zZE+zN+4zNd38rsOevjGYQvmx2y3aFYVTokncOKP4VFS8h6IUKv1ZORhoBlNMOL//T0cv8gqHegMmn+mafDYL+EdNuCCFwO5ZqlNeRqHEPPBuDjQmk+TWod1cwW608AWQE3arAp7DHOT8rEoSeN33u97ikKzhAZJgES1UZLQgqSdnlO40T0jMJK0XhPbmg5zqH9cIevNbhbaH1mtQ+ssjYjAy5n13cnB/75NW0S+bzBmfmFAR+0DuD9WzqdPbt7RU0Z+xaMWGUZ0mmItsEbm1MbLKKtfDDpEXiDTEHvH6xU5OEWA3VnqdLMazscH1xd8h+7/24hi6wzjfGUjE4eNig6OF/c1mNn76ifGi0+g5hwFTskQS9x0j3Rp/qP/8/4aT1fdYQ/n6IUVVSiiYIlsuXDVTvp4NkgUeEKj7oPwKkoxXXPcO0xCxz2TiVaiGU7MA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
