travis:
  secure:
    BINSTAR_TOKEN: uukd7au4T7UqC5lqEG7rI/kmG/VfiDQXcSwuxw35rVjW2JpIxoP4bG6W7S0JlRDwJAg3kjurw+jbkZlFkwBPRfBbcC7WGp/GOhtrHkbC9b5R9FnkYycZu9RE9dC5Y6WAlzclZAPZtvuquUrMgtqE2XDbdR1QinY3yy/NivJwoKy1fdx6dQ9YkiM5hifKlmypWEYycYff5X8ucB2cNRh6bQ0frhvvvJz8gdfSYjuoqrnwZapKpibdP+6lpyftKN3nGgucIp3H+9/cYXiyJpPS1akRhr0Oto2N7mLGUFMiMSBL3/JG2uTvjZboT6lj03ArRnxpUVRX06ZowSVM92IcM06iJ9LoQmbcGuEhngD4x3DmzwidM3juhtxAKjIsMiJ4bdpbQ/s462q595h5w5BHSe9F+HAPk4jWQIJvLszluNOdDR0gIdJ2H1cAVJGVjvA9UqBY/vFZoKsic0PGraBFQZqBHggs8ArPZXwk5zOsFxA0wCaqS7EZ+gaHrG4+SP7l1uOLBpedclk98IU+g1v+p9uOzxdksmH8pBXvk6pYFZ9rMswb+W9jgi/N7+SGMz+Ko7kXEmNKVpRrmzH4bmNNCWOKQ9vi3Pc3FLKZg/sCig1RlCy51YeVarzkgsc2XsKR6BL1GsoWaFegkcqciTFvy/DvxnUavCQLdXpBDj1GeNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
